Sprint 3
rmatafonov/middle.messenger.praktikum.yandex pull request #12
Opened 2022-04-23 19:17 UTC by rmatafonov

2022-04-24 08:30 UTC, agadoev requested changes
Привет)

Спасибо за работу, все круто. Я отметил несколько моментов, на которые стоит обратить внимание. Однако, я не могу принять ее, пока нет тестов на роутер, базовый компонент. Сейчас я их не увидел, хотя может я не туда смотрю? В общем, допиливай тесты и поедем дальше :)

2022-04-24 08:30 UTC, agadoev commented on src/service/front/router/Router.ts
> +    _onRoute(pathname: string) {
Этот метод можно сделать приватным

2022-04-24 08:30 UTC, agadoev commented on src/pages/messenger/messengerPage.ts
> +                chatsAPI.createChat(newTitle)
Здесь используется цепочка прописов это круто, однако я что произойдет, если с сервера вернется, скажем 500 ошибка? внутри метода createChat ты проверяешь этот момент, и выдаешь ошибку, но в цепочке промисов это никак пока что не обрабатывается. Может ты забыл сюда это добавить, потмоу что в других местах в проекте у тебя такие исключения обработаны в блоке .catch(). Сюда тоже неплохо было бы добавить обработку ошибок

2022-04-24 08:30 UTC, agadoev commented on src/pages/messenger/messengerPage.ts
> +                    .then(token => {
Здесь тоже не хватает обработки ошибок

2022-04-24 08:30 UTC, agadoev commented on src/pages/messenger/messengerPage.ts
> +                userAPI.userSearch(login)
И здесь тоже нужна обработка ошибок, если что-то пойдет не так

2022-04-24 08:30 UTC, agadoev commented on src/pages/messenger/messengerPage.ts
> +                            foundUsers: undefined
Можно не указывать явно undefined, потому что это свойство итак будет undefined

2022-04-24 08:30 UTC, agadoev commented on src/components/chat/chat.ts
> +    this.socket = new WebSocket(`wss://ya-praktikum.tech/ws/chats/${user?.id}/${chatId}/${token}`);
С архитектурной точки зрения было бы правильнее вынести всю логику, связанную с WebSocket, в отдельный класс, как это сделано с HttpTransport. Будет круто, если у тебя получится так сделать

2022-04-24 08:30 UTC, agadoev commented on src/components/chat/chat.ts
> +            type: 'message',
Часто когда работают с сокетами, типы событий выносят в константы, по аналогии как это сделано в Component.ts в свойстве EVENTS

2022-04-24 08:30 UTC, agadoev commented on src/components/chatsList/chatsList.ts
> +        const chatRefName = Object.keys(this.refs).find(k => this.refs[k] === chatsListItem)
Поиск рефа - это задача, которая может потребоваться в любом компоненте, поэтому лучше вынести эту логику в базовый класс Component, чтобы код не дублировался. Сейчас он дублируется пока что в двух местах, но с ростом приложения таких мест будет еще больше

2022-04-24 08:30 UTC, agadoev commented on src/components/chatsListItem/chatsListItem.ts
> +    chatsAPI.getChatUsers(this.state.id)
Здесь не хватает перехвата ошибок в блоке .catch()

2022-04-24 08:30 UTC, agadoev commented on src/components/chatsListItem/chatsListItem.ts
> +        if (description.length > 140) {
Магические числа лучше помещать в константы и называть их  в UPPER_CASE

2022-04-24 08:30 UTC, agadoev commented on src/components/link/link.ts
> +    if (this.props.onClick) {
Эту конструкцию можно записать более читаемо

{
  const defaultOnClick = (e: PointerEvent) => {...}
  this.events.click = this.props.onClick || defaultOnClick
}

2022-04-24 08:30 UTC, agadoev commented on src/dto/UserDto.ts
> +export default class UserDto {
Хорошая практика использовать Data Transfer Object, молодец)

2022-04-25 07:42 UTC, rmatafonov commented
> Привет)
> 
> Спасибо за работу, все круто. Я отметил несколько моментов, на которые стоит обратить внимание. Однако, я не могу принять ее, пока нет тестов на роутер, базовый компонент. Сейчас я их не увидел, хотя может я не туда смотрю? В общем, допиливай тесты и поедем дальше :)

Привет!
Спасибо большое!
Тесты на роутер добавил. Тут есть вопрос:
Жду вызов window.onpopstate через setTimeout - выглядит неправильно, т.к. если что-то падает, то ошибка тестов пишется просто в лог, а сам прогон тестов считается успешным. Как можно, например, дождаться, пока onpopstate произойдет и затем продолжить тест? Или же просто выставить sleep, но с ходу я что-то не нашел решения, которое выставил этот sleep...

Остальные замечания, как я понимаю, не критичные, и, в принципе, я их ожидал :), но время поджимает, я бы на неделе доработок с ними вдумчиво посидел. Сейчас параллельно с работой накосипорю, что потом буду долго разбираться, где не работает :)

И еще хочется твое мнение, правильно ли я понимаю следующее?
Есть у меня механизм, когда в messengePage по клику на найденного юзера сразу создается чат, туда добавляется этот юзер, потом в другом компоненте поднимается сокет. 
Но пользователь может тыкнуть не туда, и лучше сначала показать пользователю строку для отправки сообщения и только потом на событие отправки уже создавать чат, добавлять пользователя, и собственно, отправлять сообщение в сокет.
Верно?

2022-04-26 09:14 UTC, agadoev commented
Смотри, по поводу тестов:
Скорее всего тебе не нужно ждать вызова window.onpopstate. В методе back и forward у тебя навигация происходит засчет history.back() и history.forward(), но эти методы функции написаны не тобой, а разработчиками браузеров, и тестировать то, как они работают задача не твоя, а разработчиков браузеров. Очень важно тестировать именно свой код. Юнит тест для твоего роутера будет выглядеть очень просто - тебе надо лишь проверить, что были вызваны функции history.back() и history.forward(). 
В библиотке chai это можно сделать так https://www.chaijs.com/api/bdd/#method_throw
То, что ты написал, уже похоже на e2e тест, и такие тесты довольно сложны и для них используются совсем другие библиотеки тестирования, например cypress или selenium, можешь потыкать их

2022-04-26 09:24 UTC, agadoev commented
Тыкнуть не туда - ты имеешь в виду не на того пользователя? В таком случае да, звучит логично, похожим образом сейчас сделано в telegram. Единственное, что я бы добавил - прежде чем добавлять пользователя в чат, нужно удостовериться, что сообщение было отправлено. Чтобы не было такой ситуации, что например человек №1 отправляет сообщение человеку №2, оно по какой-либо причине не доставляется, а человек №2 добавляется в пустой чат

2022-04-26 09:25 UTC, agadoev commented
В целом работа мне понравилась, есть потенциал, я ее принимаю)

Успехов в дальнейшем)

2022-04-28 07:21 UTC, merged